name: End-to-end tests
on:
  workflow_dispatch:
    inputs:
#      amb:
#        description: 'Selecionar algum destes ambientes: dev / hlg / prd'
#        required: false
#        default: 'hlg'
      browser:
        description: 'Selecionar algum destes browsers: chrome / electron'
        required: false
        default: 'chrome'
#      tag:
#        description: 'Selecionar alguma tag, por exemplo: @regressivo / @smoke / @login'
#        required: false
#        default: '@regressivo'
  pull_request:
    branches: [ main ]
  schedule:
    #(minuto - hora - dia do mês - mês - dia da semana)
    - cron: "0 0 1 * *"
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
            allure_results: allure-results
            allure_history: allure-history
            keep_reports: 20
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
            PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PUBLISH_BRANCH: gh-pages
            PUBLISH_DIR: allure-history
